const randomEl = (list) => {
  var i = Math.floor(Math.random() * list.length);
  return list[i];
}

export const generateRandomName = () => {
  return randomEl(adjectives) + " " + randomEl(nouns);
}

const adjectives = ["silly", "funny", "goofy", "green", "yellow", "melted", "smelly", "rotten", "shaggy", "gorgeous", "annoyed", "purple", "pink", "sad", "happy", "gassy", "amused", "evil", "bright", "brave", "beautiful", "pretty", "tricky", "tough", "sweet", "fair", "cold", "hot", "warm", "toasty", "confused", "foolish", "sour", "spicy", "solid", "soft", "squishy", "small", "large", "enormous", "fresh", "crazy", "long", "short", "smart", "young", "old", "strong", "cool", "fuzzy", "steep", "flat", "flaky", "bumpy", "fluffy", "quick", "chilly", "cheerful", "blue", "excited", "kind", "gray", "loyal", "witty", "sassy", "clean", "curious", "friendly", "grateful", "nervous", "proud", "lovely", "modest", "mild", "sleepy", "shy", "sensible", "sensitive", "sharp", "quiet", "eager", "musical", "groggy", "crabby", "cranky", "clumsy", "confident", "crafty", "lively", "logical", "helpful", "noisy", "loud", "plain", "picky", "patient", "polite", "serious", "snazzy", "jolly", "merry", "wise"];
const nouns = ["apple", "banana", "grape", "pear", "kiwi", "book", "caterpillar", "poptart", "monkey", "wombat", "doodle", "goat", "coffee", "sandwich", "kitten", "island", "dragon", "elf", "toilet", "lettuce", "soda", "chef", "cake", "president", "puppy", "candle", "snake", "pie", "cupcake", "noodle", "spaghetti", "cheese", "pizza", "guppy", "tadpole", "lizard", "squirrel", "otter", "chicken", "camel", "creature", "squid", "bee", "octopus", "spatula", "zebra", "drummer", "cloud", "mosquito", "magnet", "robot", "popcorn", "desk", "snickerdoodle", "gnome", "sock", "puffin", "toast", "wizard", "zombie", "ogre", "goggle", "duck", "ketchup", "mustard", "steak", "bagpipe", "antelope", "milkshake", "berry", "barbeque", "worm", "fever", "salad", "night", "pocket", "salt", "pepper", "mustache", "beard", "bathroom", "disco", "sunshine", "storm", "parade", "sheep", "crow", "meme", "paddle", "kangaroo", "rice", "mountain", "soccer", "cookie", "cave", "sweater", "winter", "summer", "motorcycle", "door"];